services:
  - type: web
    name: emotion-recognition
    env: node
    plan: free
    branch: main
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: "10000"